- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- app/models/item.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/user.rb
- db/migrate/20190520223842_create_users.rb
- db/migrate/20190520224220_create_items.rb
- db/migrate/20190520224940_create_orders.rb
- db/migrate/20190520225214_create_order_items.rb
- db/schema.rb
- spec/models/item_spec.rb
- spec/models/order_item_spec.rb
- spec/models/order_spec.rb
- spec/models/user_spec.rb
This PR adds all database migrations and model relationships.
- Add Order, OrderItems, User, Item migrations, models and spec files
- Add relationships to all models, with relationship specs
> Database Migrations

- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- config/routes.rb
- spec/features/items/index_spec.rb
This PR adds an Item index with all relevant Item information.
- Each Item in the database is displayed in a list, with the Item's name, seller, available quantity, and price
- The Item's name and picture are links to an Item show page
- Added a route for the Item show page for testing purposes
> Items Index

- app/controllers/sessions_controller.rb
- spec/features/session/login_spec.rb
It's one commit lol that's all it took
> Add warning to redirection to satisfy Story 11

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/index.html.erb
- spec/features/items/index_spec.rb
- spec/models/item_spec.rb
- spec/rails_helper.rb
This PR adds statistics to the Items index.
- Statistics include the top 5 most/least popular Items, along with the total amount of that Item that has been ordered
- Popularity is calculated by total quantity of that Item that has been sold
- most/least_popular class methods have been added to Items model with the appropriate specs
- ItemsController index action has been updated to avoid calling class methods in the view
> Items Index Stats

- app/models/order.rb
- app/models/user.rb
- spec/models/user_spec.rb
This PR starts user story 36.
- Add additional test data to User model spec
- Add top_five_items instance method to User model with spec
- Add enum ["pending", "packaged", "shipped", "cancelled"] to User model
> User Story 36 Start

- app/controllers/application_controller.rb
- app/controllers/carts_controller.rb
- app/models/cart.rb
- app/views/layouts/application.html.erb
- spec/features/cart/show_spec.rb
- spec/features/welcome/index_spec.rb
- spec/models/cart_spec.rb
This PR
-Adds cart link to navigation
-Adds cart quantity to navigation
-does minor refactors for readability
-Adds spec for link and quantity
> Add cart to navigation

- app/controllers/profile/orders_controller.rb
- app/models/order.rb
- app/views/profile/orders/index.html.erb
- config/routes.rb
- spec/features/users/orders/index_spec.rb
- spec/models/order_spec.rb
This PR Completes user order show by
-Adding link to individual order pages  
--which involved creating those pages and that route
-Adding order created at and updated at  to profile order
-Adding item count and price to profile order
--which involved creating order model total_price and total_number_of_items method and specs
> User profile order page

- app/controllers/profile/orders_controller.rb
- app/models/item.rb
- app/views/profile/orders/show.html.erb
- db/schema.rb
- spec/features/users/orders/show_spec.rb
- spec/models/item_spec.rb
This PR
-Adds a user order show page and corresponding spec
-Adds an item find_order_item method and spec
-Puts orders stats and stats for each item in an order on that show page
> User order show page

- spec/features/users/orders/show_spec.rb
- spec/rails_helper.rb
Co-Authored-By: null <Patrick-Duvall@users.noreply.github.com>
Co-Authored-By: Alexander Mathieu <alexander-mathieu@users.noreply.github.com>
Removed save_and_open_page mine
Added factory bots to simplecov's filter
> Remove save_and_open_page and add factories omission to simplecov

- app/views/merchants/show.html.erb
- spec/factories/user.rb
- spec/features/merchants/show_spec.rb
- spec/features/users/show_spec.rb
- Added merchant attributes for merchant dashboard view with a new spec file in features/merchants
- Removed some factory bot attributes now that I know child bots inherit attributes from their parents
- Removed some user story comments from the user show spec
> Merchant dash story 34

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/new.html.erb
- app/views/merchants/show.html.erb
- config/routes.rb
- db/schema.rb
- spec/factories/item.rb
- spec/features/merchants/add_item_spec.rb
> Merchant add

- spec/features/merchants/index_spec.rb
- spec/features/merchants/orders/show_spec.rb
This PR
- Removes saop and puts
> Remove saop

- app/controllers/merchants/orders_controller.rb
- app/views/merchants/orders/show.html.erb
- config/routes.rb
- spec/features/merchants/orders/show_spec.rb
This PR 
-Adds ability of merchant to fulfill part of an order
-Adds button to fulfill an order on merchant order show
--This button only shows up if merchant has inventory to fulfill and order is unfulfilled
-Adds controller update action which
--updates order_item to fulfilled
--reduces item inventory
-Lets merchant know order has been fulfilled
> Merchant fulfills part of order

- app/models/order.rb
- app/views/merchants/orders/show.html.erb
- db/schema.rb
- spec/features/merchants/orders/show_spec.rb
- spec/features/users/orders/show_spec.rb
- spec/models/order_spec.rb
This PR
-Makes cancelling an order refund item stock
-Adds spec at model and feature level
> Cancel order refunds items

- app/views/merchants/orders/show.html.erb
- db/schema.rb
- spec/features/merchants/orders/show_spec.rb
This PR 
-Adds a red notice on merchant order show if merchant has insufficient inventory
-changes logic for displaying "order fulfilled" message
-uses inline html so it wont be overwritten
> Big red notice

- app/views/layouts/application.html.erb
> hotfix the navbar

- spec/models/item_spec.rb
This PR adds Item model specs for enable/disable instance methods.
> Add Item Model Specs

- app/models/order.rb
- spec/features/admin/dashboard/index_spec.rb
This PR
-Changes LogIn to Login
-Adds absent end
> Hotfix master merge

- app/controllers/admin/orders_controller.rb
- app/views/admin/orders/index.html.erb
- spec/features/admin/orders/index_spec.rb
This PR adds an Admin Order index for a user.
- Add Admin Order index spec
- Add Admin Order index view
> Admin User Orders Index

- app/controllers/carts_controller.rb
- app/controllers/users_controller.rb
> Should be all of it.

- app/controllers/carts_controller.rb
- app/controllers/sessions_controller.rb
- app/views/users/edit.html.erb
- spec/features/users/edit_spec.rb
This PR
-Makes it so users can log in, change password, log out, then use changed PW to log back in
-Hotfix in carts controller for nil error on merchant if no user.
> Pass word change

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/admin/merchants_controller.rb
- app/controllers/sessions_controller.rb
- app/views/carts/show.html.erb
- app/views/layouts/application.html.erb
- app/views/profile/orders/index.html.erb
- app/views/profile/orders/show.html.erb
- app/views/users/show.html.erb
- app/views/welcome/index.html.erb
- spec/features/session/login_spec.rb
- spec/features/users/orders/index_spec.rb
- spec/models/cart_spec.rb
Some little things here and there missing with the styling. Mostly buttons and stuff.
Also adds the cart model tests.
> Final Touches

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/admin/merchants_controller.rb
- app/controllers/sessions_controller.rb
- app/models/user.rb
- app/views/carts/show.html.erb
- app/views/layouts/application.html.erb
- app/views/profile/orders/index.html.erb
- app/views/profile/orders/show.html.erb
- app/views/users/show.html.erb
- app/views/welcome/index.html.erb
- db/migrate/20190520223842_create_users.rb
- db/schema.rb
- spec/features/session/login_spec.rb
- spec/features/users/orders/index_spec.rb
- spec/models/cart_spec.rb
This PR
-Fixes pending order user instance test
-Adds active default true to user in DB
-Also merges final touches
> Migration and pending

- spec/models/cart_spec.rb
This PR adds a test to the Cart model to get us to 100% coverage.
> Add Final Cart Test

- app/controllers/admin/dashboard_controller.rb
- app/views/admin/users/index.html.erb
- spec/features/admin/users/index_spec.rb
This PR fixes the Admin User upgrade button.
- Add appropriate path to 'Upgrade to Merchant' button
- Add Admin feature spec for user being upgraded to merchant
> Fix Admin User Upgrade

- app/models/order.rb
- spec/features/merchants/orders/show_spec.rb
- spec/models/order_spec.rb
This PR
-Adds more resiliant tests for fulfilled order
> Add more resialiant tests
